### ISSUE TITLE
Steam Deck use?

### ISSUE THREAD

**Issue by rafael1303** [sneakyevil/SD-ModMenu#118]
Hi, 

I know it's a long shot, will you be able to mod this menu to be playable for **steam deck users**?

SD community will appreciate this. 

Looking forward to hearing from you. 
Regards and thanks

**Comment by sneakyevil** [comment]
The menu is compatible with controller and as such it works fine on steam deck since I own it myself. You just need to follow the installation and have launch option for the game as `WINEDLLOVERRIDES="dinput8=n,b" %command%` to allow ASI loader to work under a wine/proton.

**Comment by rafael1303** [comment]
Thank you!

**Comment by rafael1303** [comment]
Hi, the mod menu is the opening for steam deck and I have done everything on the readme file. :(

please help.
