### ISSUE TITLE
Model Changer: Option to Make Female Models Size match that of Male Models

### ISSUE THREAD

**Issue by menganese** [sneakyevil/SD-ModMenu#63]
This appears consistent with how the models are rendered in the game vanilla, but given that the player model is originally a male model, it would be nice if the female models in the model changer were sized up to match that of the male models as some of the player-specific animations currently don't sync up as nicely for the female models.

============
By the way, great job on this mod. It's the greatest thing I've seen in years and had given up hope that this game would be moddable, so thanks and kudos for taking on the task and doing it so well. I noticed that all of the female models are smaller than the male models.

**Comment by sneakyevil** [comment]
Closing this as this was moved to Sponsor's repository issues.
