### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by VolvoAdidas** [sneakyevil/SD-ModMenu#83]
Hi sneakyevil and thank you for what you do. I've been waiting for something like this for years. A couple of suggestions though.

1. It would be nice if we could set npcs health for more than 200. I mean with 200 they die pretty quickly and with npcs godmode on it obviously takes forever. Something like 4000 would be perfect.

2. I've noticed that Winston as a player model doesn't have mouth animations. You can check it trying to sing karaoke as Winston.

3. I also suggest renaming Dogboys to Jade Gang, because, well, it is their correct name.

**Comment by sneakyevil** [comment]
No idea if the mouth animations can even be fixed, the animations stuff are mostly based on bone indexes under havok engine which I have no clue how it even works, but other stuff can be easily done.

**Comment by sneakyevil** [comment]
I invited you to the sponsor repository and made those 2 changes, I gonna close this as completed. I will try look at the winston mouth animations later on, but I feel like I won't be able to fix that if its related to Havok Animations stuff.

**Comment by VolvoAdidas** [comment]
Ok, thank you much!
